{{- if eq .Values.nodeType "producer" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-certificates
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.nodeType }}
    app.kubernetes.io/name: cardano-node
type: kubernetes.io/opaque
stringData:
  "kes.skey": |-
{{ .Values.producerCertificatesKesSKey | trim | indent 4 }}
  "vrf.skey": |-
{{ .Values.producerCertificatesVrfSKey | trim | indent 4 }}
  "node.cert": |-
{{ .Values.producerCertificatesNodeCert | trim | indent 4 }}
{{- end }}
