apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.nodeType }}
    app.kubernetes.io/name: cardano-node
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.nodeType }}
    app.kubernetes.io/name: cardano-node
  ports:
    - name: cardano
      protocol: TCP
      port: {{ .Values.nodePort }}
      targetPort: {{ .Values.nodePort }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
